In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load data
df = pd.read_csv("../data/raw/Traffic_Study_Flow_Counts.csv")

# Basic check
print(df.shape)
print(df.columns.tolist())
df.head()

(61919, 35)
['OBJECTID', 'STUDY_ID', 'TITLE', 'START_DATE', 'END_DATE', 'ACTUAL_DAYS', 'INTENDED_DAYS', 'STUDY_LENGTH', 'STUDY_LANE_CODE', 'STUDY_DIRFLOW', 'COMMENTS', 'STUDY_ADT', 'STUDY_AWDT', 'STUDY_MAX8', 'STUDY_AMPK', 'STUDY_PMPK', 'SEG_COMPKEY', 'UNITID', 'UNITID2', 'O_STREET', 'X_STREET', 'DIR_FROM_CROSS_STREET', 'STDY_TITLE_PART', 'STDY_LABEL', 'DISTANCE', 'STDY_YEAR', 'STUDY_TYPE', 'FLOWMAP', 'HPMS', 'SCREENLINE', 'ONE_HOUR_REPORT_URL', 'SE_ANNO_CAD_DATA', 'STDY_TITLE_PART_WITH_FLOW', 'x', 'y']

,OBJECTID,STUDY_ID,TITLE,START_DATE,END_DATE,ACTUAL_DAYS,INTENDED_DAYS,STUDY_LENGTH,STUDY_LANE_CODE,STUDY_DIRFLOW,...,STDY_YEAR,STUDY_TYPE,FLOWMAP,HPMS,SCREENLINE,ONE_HOUR_REPORT_URL,SE_ANNO_CAD_DATA,STDY_TITLE_PART_WITH_FLOW,x,y
0,17091897,102216,"M L KING JR WAY S, S/O S BRADFORD ST; N FLOW; ...",8/15/2002 2:00:00 PM,8/22/2002 2:00:00 PM,7,7,672,0,N,...,2002,VOLUME COUNT,NaN,NaN,NaN,http://wdcsqlpwrk03/ReportServer/Pages/ReportV...,System.Byte[],"M L KING JR WAY S, S/O S BRADFORD ST; N FLOW",1.279114e+06,210848.283276
1,17091898,206214,"3RD AVE, NW/O LENORA ST; SE FLOW; CH1; 01MAR20...",3/1/2005 11:15:00 AM,3/8/2005 10:00:00 AM,7,7,672,STANDARD,SE,...,2005,VOLUME COUNT,NaN,NaN,Y,http://wdcsqlpwrk03/ReportServer/Pages/ReportV...,System.Byte[],"3RD AVE, NW/O LENORA ST; SE FLOW",1.268118e+06,227455.995549
2,17091899,217843,"WESTLAKE AVE N, N/O THOMAS ST; N FLOW; CH1; 05...",11/5/2009 1:00:00 PM,11/12/2009 1:00:00 PM,7,7,672,STANDARD,N,...,2009,VOLUME COUNT,NaN,Y,NaN,http://wdcsqlpwrk03/ReportServer/Pages/ReportV...,System.Byte[],"WESTLAKE AVE N, N/O THOMAS ST; N FLOW",1.269255e+06,230318.510752
3,17091900,93239,"LAKE DELL AVE, NE/O 32ND AVE; SW FLOW; 13DEC20...",12/13/2001 1:00:00 PM,12/20/2001 1:00:00 PM,7,7,672,0,SW,...,2001,VOLUME COUNT,NaN,NaN,NaN,http://wdcsqlpwrk03/ReportServer/Pages/ReportV...,System.Byte[],"LAKE DELL AVE, NE/O 32ND AVE; SW FLOW",1.281084e+06,223160.366809
4,17091901,101507,"BEACH DR SW, SE/O 61ST AVE SW; N FLOW; 04JUN20...",6/4/2002 11:00:00 AM,6/11/2002 11:00:00 AM,7,7,672,0,N,...,2002,VOLUME COUNT,NaN,NaN,NaN,http://wdcsqlpwrk03/ReportServer/Pages/ReportV...,System.Byte[],"BEACH DR SW, SE/O 61ST AVE SW; N FLOW",1.251128e+06,212159.535629

In [5]:
# Filter to 2026 only
df_2026 = df[df["STDY_YEAR"] == 2026].copy()

print("Rows in 2026:", len(df_2026))

Rows in 2026: 836

In [6]:
# Kep only columns needed for this assignment
df_2026 = df_2026[["O_STREET", "X_STREET", "STUDY_ADT"]].copy()

df_2026.head()

          O_STREET            X_STREET  STUDY_ADT
2075    3RD AVE NW          NW 86TH ST       3898
2179  FLORENTIA ST  QUEEN ANNE E AVE N       2931
2260  NW MARKET ST          8TH AVE NW      11035
2322   W DRAVUS ST          20TH AVE W       1457
2374   18TH AVE SW       SW BRANDON ST        264

In [7]:
# Clean street text
# Change value type to string and remove whitespaces just in case
df_2026["O_STREET"] = df_2026["O_STREET"].astype(str).str.strip()
df_2026["X_STREET"] = df_2026["X_STREET"].astype(str).str.strip()

# Turn fake "nan" strings back to real missing values so they can be removed easily
df_2026[["O_STREET", "X_STREET"]] = df_2026[["O_STREET", "X_STREET"]].replace("nan", np.nan)

# Clean traffic values
df_2026["STUDY_ADT"] = pd.to_numeric(df_2026["STUDY_ADT"], errors = "coerce")

# Remove rows missing needed values
df_2026 = df_2026.dropna(subset = ["O_STREET", "STUDY_ADT"]).copy()

print("Rows after cleaning: ", len(df_2026))
df_2026.head()

Rows after cleaning:  836

          O_STREET            X_STREET  STUDY_ADT
2075    3RD AVE NW          NW 86TH ST       3898
2179  FLORENTIA ST  QUEEN ANNE E AVE N       2931
2260  NW MARKET ST          8TH AVE NW      11035
2322   W DRAVUS ST          20TH AVE W       1457
2374   18TH AVE SW       SW BRANDON ST        264

In [8]:
# Create one location label for the chart
df_2026["LOCATION"] = np.where(
    df_2026["X_STREET"].notna(),
    df_2026["O_STREET"] + " & " + df_2026["X_STREET"],
    df_2026["O_STREET"]
)

df_2026.head()

,O_STREET,X_STREET,STUDY_ADT,LOCATION
2075,3RD AVE NW,NW 86TH ST,3898,3RD AVE NW & NW 86TH ST
2179,FLORENTIA ST,QUEEN ANNE E AVE N,2931,FLORENTIA ST & QUEEN ANNE E AVE N
2260,NW MARKET ST,8TH AVE NW,11035,NW MARKET ST & 8TH AVE NW
2322,W DRAVUS ST,20TH AVE W,1457,W DRAVUS ST & 20TH AVE W
2374,18TH AVE SW,SW BRANDON ST,264,18TH AVE SW & SW BRANDON ST

In [9]:
# Aggregate by location taking mean for same location entries having multiple ADT records
traffic_by_location = (
    df_2026.groupby("LOCATION", as_index = False)
    .agg(avg_adt = ("STUDY_ADT", "mean"))
)

traffic_by_location.head()

                    LOCATION      avg_adt
0  10TH AVE NE & NE 127TH ST   339.333333
1  10TH AVE W & W WHEELER ST  1082.666667
2       11TH AVE & E PIKE ST  1248.666667
3  11TH AVE W & W BARRETT ST  2630.666667
4   11TH AVE W & W DRAVUS ST  2032.000000

In [10]:
# Sort from highest to lowest traffic
traffic_by_location = traffic_by_location.sort_values(
    by = "avg_adt",
    ascending = False
).reset_index(drop = True)

traffic_by_location["avg_adt"] = traffic_by_location["avg_adt"].round(2)

traffic_by_location.head(20)

                                       LOCATION   avg_adt
0   WEST SEATTLE BR EB & ALASKAN WY VI NB ON RP  72615.67
1                  WEST SEATTLE BR EB & POINT A  35862.25
2             EAST MARGINAL WAY S & S ALASKA ST  34868.80
3                 LAKE CITY WAY NE & NE 95TH ST  28782.00
4                  WEST SEATTLE BR WB & POINT A  20754.00
5                       UNIVERSITY BR & POINT A  19606.00
6                 UNIVERSITY BR & FUHRMAN AVE E  18857.67
7                     AURORA AVE N & N 141ST ST  18155.33
8                     AURORA AVE N & N 109TH ST  17236.00
9                     AURORA AVE N & N 130TH ST  16869.00
10                    AURORA AVE N & N 117TH PL  16716.67
11                       DENNY WAY & 2ND WR AVE  16124.44
12                N 85TH ST & INTERLAKE E AVE N  15769.90
13                  35TH AVE SW & SW AVALON WAY  14414.67
14                    NW MARKET ST & 8TH AVE NW  13860.78
15                         FREMONT BR & POINT A  13207.50
16                   SW HOLDEN ST & 11TH AVE SW  12947.33
17        M L KING JR ER WAY S & RENTON N AVE S  12094.50
18                 RAINIER AVE S & S OTHELLO ST  11557.60
19                 35TH AVE SW & SW HOLDEN S ST  10270.67

In [11]:
# Keep only top 15 for cleaner Flourish bar chart
top_15_traffic = traffic_by_location.head(15).copy()

top_15_traffic

                                       LOCATION   avg_adt
0   WEST SEATTLE BR EB & ALASKAN WY VI NB ON RP  72615.67
1                  WEST SEATTLE BR EB & POINT A  35862.25
2             EAST MARGINAL WAY S & S ALASKA ST  34868.80
3                 LAKE CITY WAY NE & NE 95TH ST  28782.00
4                  WEST SEATTLE BR WB & POINT A  20754.00
5                       UNIVERSITY BR & POINT A  19606.00
6                 UNIVERSITY BR & FUHRMAN AVE E  18857.67
7                     AURORA AVE N & N 141ST ST  18155.33
8                     AURORA AVE N & N 109TH ST  17236.00
9                     AURORA AVE N & N 130TH ST  16869.00
10                    AURORA AVE N & N 117TH PL  16716.67
11                       DENNY WAY & 2ND WR AVE  16124.44
12                N 85TH ST & INTERLAKE E AVE N  15769.90
13                  35TH AVE SW & SW AVALON WAY  14414.67
14                    NW MARKET ST & 8TH AVE NW  13860.78

In [12]:
# Save aggregated and cleaned csv file for Flourish
top_15_traffic.to_csv("../data/processed/top_15_traffic_locations_2026.csv", index = False)